spring.application.name=gestao-visitantes

spring.datasource.url=jdbc:postgresql://udggxlfrhiccfiwvfupv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=giovanna85912612
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true
